version: "3"
services:
  fatura_db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data1
    environment:
      POSTGRES_PASSWORD: rpg
      POSTGRES_USER: rpg
      POSTGRES_DB: rpg_avanade
    ports:
      - "5433:5432"

volumes:
  db-data:
    driver: local